---
- debug:
    msg: "product_family: {{ app_v2_product_family }} ; release: {{ app_v2_release }}"
  tags:
    - app_v2
    - app_v2_debug

- name: "{{ app_v2_product_family }} - check if mandatory deployment parametres are provided"
  fail:
    msg: "mandatory deployment parametres not provided!"
  when: app_v2_product_family ==  "" or app_v2_release == ""
  tags:
    - app_v2

- name: "{{ app_v2_product_family }} - create app directory"
  file:
    path: "{{ app_v2_basedir }}"
    state: directory
    mode: "0750"
  notify: touch to reload
  tags:
    - app_v2

- name: "{{ app_v2_product_family }} - change app directory mode"
  file:
    path: "{{ app_v2_basedir }}"
    mode: "0770"
  notify: touch to reload
  tags:
    - app_v2

- name: Handle touch to reload file exists
  copy:
    content: ""
    dest: "{{ app_v2_touch_to_reload_file }}"
  tags:
    - app_v2
...
